Bug fix for identically named timers trace names
This fixes a bug noted by Thomas Klepp which causes the ATMega128 to fail upon
instantiation. When running 'make run_sim' in regress/avrtest, it fails with:

*** Running until timeout ***
../../src/simulavr --device atmega128 -f maxruntime \
            -W 0x52,- -m 1000000

ERROR: file traceval.cpp: line 263: Internal error: Tracevalue
'TIMER1.TCCRA' already registered.

This patch fixes this issue by giving the timers in the mega128 proper names
and, more generally, allows all timers to be numbered upon creation in the
containing AvrDevice object.